CREATE TABLE stores(
	store_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	store_name INTEGER:VARCHAR(150) NOT NULL,
	address_line_1 VARCHAR(255) NOT NULL,
	address_line_2 VARCHAR(100),
	city_id INT NOT NULL,
	state_id INT NOT NULL,
	district_id INT NOT NULL,
	zip_code VARCHAR(6),
	PRIMARY KEY (store_id)
);

   CREATE TABLE CUSTOMER
     (CUSTOMERNUM      INTEGER,
      CUSTOMERNAME     VARCHAR(80),
      ADDRESS          VARCHAR(200),
      CITY             VARCHAR(50),
      COUNTRY          VARCHAR(50),
      CODE             VARCHAR(15)
      PRIMARY KEY (CUSTOMERNUM));

  CREATE TABLE PROJ
     (PROJNO   CHAR(6)      NOT NULL,
      PROJNAME VARCHAR(24)  NOT NULL,
      DEPTNO   CHAR(3)      NOT NULL,
      RESPEMP  CHAR(6)      NOT NULL,
      PRSTAFF  DECIMAL(5,2)         ,
      PRSTDATE DATE                 ,
      PRENDATE DATE                 ,
      MAJPROJ  CHAR(6)      NOT NULL);

